$(function(){
	var html = "";
	html+="<div class='panel'>";
	html+="	<div class='mainbtn'>";
	html+="<div style='float:left;'>";
	html+="<input class='btn' type='button' id='agentLogin_login' value='签入'/>";
	html+="<input class='btn' type='button' id='agentLogin_logout' value='签出'/>";
	html+="<input class='btn' type='button' id='agentCallAnswer' value='应答'/>";
	html+="<input class='btn' type='button' id='agentCallHangup' value='挂机'/>";
	html+="<input class='btn' type='button' id='agentStatusSayIdle' value='示闲'/>";
	html+="<input class='btn' type='button' id='agentStatusSayBusy' value='示忙'/>";
	html+="<span class='autoAnswer'>自动应答：</span>";
	html+="<input type='radio' value='0' name='agentSetting_autoAnswer'/>";
	html+="<label class='autoAnswer'>Yes</label>";
	html+="<input type='radio' value='1' name='agentSetting_autoAnswer' checked='checked'/>";
	html+="<label class='autoAnswer'>No</label>";
	html+="</div>";
	html+="<table class='state_m1'>";
	html+="<tr>";
	html+="<td width='110'>工号：<span id='workNo'></span></td>";
	html+="<td width='190'>主叫号码：<span id='caller'></span></td>";
	html+="<td>状态：<span id='workStatus'></span></td>";
	html+="</tr>";
	html+="<tr>";
	html+="<td>座机：<span id='callId'></span></td>";
	html+="<td>被叫号码：<span id='called'></span></td>";
	html+="<td>通话时长：<span id='callDuration'></span></td>";
	html+="</tr>";
	html+="</table>";
	html+="</div>";
	html+="</div>";
	html+="<input value='' type='hidden' id='agentLogin_agentId'>";
	html+="<input value='' type='hidden' id='agentLogin_password'>";
	html+="<input value='' type='hidden' id='agentLogin_phonenumber'>";
	html+="<input value='' type='hidden' id='winFlag'>";
	html+="<input value='' type='hidden' id='contentData'>";
	html+="<input value='aa' type='button' id='aa' onclick='test();'>";
	$("#agentDemo").append(html);
});
